"""
Creativity Engine Models — Phase 10
All dataclasses used across the creativity & innovation subsystem.
Maintains 100% backward compatibility with existing model fields while
introducing rich context, design thinking, concept synthesis, innovation,
audit replay, and evaluation structures.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Any, Dict, List, Optional


@dataclass
class CreativeContext:
    """Reusable multi-agent creative context."""
    conversation_context: Dict[str, Any] = field(default_factory=dict)
    memory_context: Dict[str, Any] = field(default_factory=dict)
    decision_context: Dict[str, Any] = field(default_factory=dict)
    reasoning_context: Dict[str, Any] = field(default_factory=dict)
    planning_context: Dict[str, Any] = field(default_factory=dict)
    learning_context: Dict[str, Any] = field(default_factory=dict)
    emotion_context: Dict[str, Any] = field(default_factory=dict)
    language_context: Dict[str, Any] = field(default_factory=dict)
    domain: str = "general"
    goals: List[str] = field(default_factory=list)
    constraints: List[str] = field(default_factory=list)
    previous_ideas: List[Any] = field(default_factory=list)
    request_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    trace_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    system_state: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class IdeaScore:
    """Configurable multi-metric score for creative evaluation."""
    novelty: float = 0.0
    feasibility: float = 0.0
    usefulness: float = 0.0
    impact: float = 0.0
    clarity: float = 0.0
    complexity: float = 0.0
    resource_requirements: float = 0.0
    implementation_difficulty: float = 0.0
    risk_level: float = 0.0
    confidence: float = 0.0
    overall: float = 0.0
    label: str = "acceptable"  # excellent / good / acceptable / poor

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CreativeIdea:
    """Representation of an idea generated by the Creativity Engine."""
    idea_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    concept: str = ""
    approach: str = ""
    implementation: str = ""
    strategy: str = ""          # brainstorm / scamper / lateral / analogical / synthesis / design_thinking / etc.
    domain: str = ""
    score: Optional[IdeaScore] = None
    version: int = 1
    parent_id: Optional[str] = None
    risk_assessment: Dict[str, Any] = field(default_factory=dict)
    cost_benefit: Dict[str, Any] = field(default_factory=dict)
    prototype_specs: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class DesignThinkingSession:
    """Structured Design Thinking workflow representation."""
    session_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    domain: str = ""
    empathy_context: Dict[str, Any] = field(default_factory=dict)
    problem_definition: Dict[str, Any] = field(default_factory=dict)
    how_might_we_statements: List[str] = field(default_factory=list)
    ideas: List[CreativeIdea] = field(default_factory=list)
    prototypes: List[Dict[str, Any]] = field(default_factory=list)
    testing_plan: Dict[str, Any] = field(default_factory=dict)
    iteration_history: List[Dict[str, Any]] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ConceptSynthesisResult:
    """Result of multi-domain concept synthesis and fusion."""
    synthesis_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source_domains: List[str] = field(default_factory=list)
    source_concepts: List[str] = field(default_factory=list)
    synthesized_concept: str = ""
    fusion_mechanism: str = ""
    concept_hierarchy: Dict[str, Any] = field(default_factory=dict)
    innovation_opportunities: List[str] = field(default_factory=list)
    confidence: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class InnovationPlan:
    """Structured innovation plan representation."""
    plan_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    domain: str = ""
    innovation_type: str = "incremental"  # incremental, radical, process, product, service, workflow, architecture
    objectives: List[str] = field(default_factory=list)
    ideas: List[CreativeIdea] = field(default_factory=list)
    roadmap: List[Dict[str, Any]] = field(default_factory=list)
    future_plugins: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CreativeAuditTrail:
    """Audit entry for creative decision explainability."""
    entry_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str = ""
    request_id: Optional[str] = None
    correlation_id: Optional[str] = None
    trace_id: Optional[str] = None
    action: str = ""
    strategy: str = ""
    input_summary: Dict[str, Any] = field(default_factory=dict)
    supporting_knowledge: List[str] = field(default_factory=list)
    reasoning_summary: str = ""
    decisions_made: List[Dict[str, Any]] = field(default_factory=list)
    alternatives_considered: List[str] = field(default_factory=list)
    recommendation_rationale: str = ""
    confidence: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CreativeAuditSnapshot:
    """Full snapshot of a session state for replay and auditability."""
    session_id: str = ""
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    context: Dict[str, Any] = field(default_factory=dict)
    ideas_generated: List[Dict[str, Any]] = field(default_factory=list)
    audit_entries: List[Dict[str, Any]] = field(default_factory=list)
    metrics_snapshot: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ReplayResult:
    """Result of replaying a past creative session."""
    session_id: str = ""
    replayed_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    original_idea_count: int = 0
    replayed_idea_count: int = 0
    match_rate: float = 1.0
    replayed_ideas: List[Dict[str, Any]] = field(default_factory=list)
    audit_trail: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CreativeSession:
    """Tracks a single operational creative session."""
    session_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    started_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    ended_at: Optional[str] = None
    request_id: Optional[str] = None
    correlation_id: Optional[str] = None
    trace_id: Optional[str] = None
    domain: str = ""
    strategy: str = ""
    ideas_generated: int = 0
    ideas_accepted: int = 0
    quality_scores: List[float] = field(default_factory=list)
    audit_entries: List[CreativeAuditTrail] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        return d

    def avg_quality(self) -> float:
        if not self.quality_scores:
            return 0.0
        return round(sum(self.quality_scores) / len(self.quality_scores), 4)


@dataclass
class CreativityMetrics:
    """Aggregated operational metrics for the Creativity Engine."""
    total_sessions: int = 0
    total_ideas_generated: int = 0
    total_ideas_accepted: int = 0
    brainstorm_count: int = 0
    scamper_count: int = 0
    lateral_count: int = 0
    analogical_count: int = 0
    synthesis_count: int = 0
    design_thinking_count: int = 0
    innovation_count: int = 0
    evaluation_count: int = 0
    replay_count: int = 0
    error_count: int = 0
    total_processing_ms: float = 0.0

    def as_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def acceptance_rate(self) -> float:
        if self.total_ideas_generated == 0:
            return 0.0
        return round(self.total_ideas_accepted / self.total_ideas_generated, 4)

    def avg_processing_ms(self) -> float:
        total_ops = (self.brainstorm_count + self.scamper_count + self.lateral_count +
                     self.analogical_count + self.synthesis_count + self.design_thinking_count +
                     self.innovation_count + self.evaluation_count + self.replay_count)
        return round(self.total_processing_ms / max(1, total_ops), 2)
